修改ck插件，增加自动建表功能，增加save_mode,order_keys参数
cloudnativecube/waterdrop pull request #6
Opened 2020-11-18 07:34 UTC by mxzlxy

修改ck插件：
1.支持自动建表，常用类型自动转换；
2.新增save_mode，order_keys参数；

2020-11-19 04:54 UTC, mdianjun requested changes
注释都用英文。 @mxzlxy

2020-11-19 04:54 UTC, mdianjun commented on plugin-spark-sink-clickhouse/src/main/scala/io/github/interestinglab/waterdrop/spark/sink/Clickhouse.scala
> +        createTable(data.schema, conn)
检查建表的返回值是否成功

2020-11-19 04:54 UTC, mdianjun commented on plugin-spark-sink-clickhouse/src/main/scala/io/github/interestinglab/waterdrop/spark/sink/Clickhouse.scala
> +    } finally {
如果有异常抛出，要捕获一下。如SQLException。

2020-11-19 04:54 UTC, mdianjun commented on plugin-spark-sink-clickhouse/src/main/scala/io/github/interestinglab/waterdrop/spark/sink/Clickhouse.scala
> +    conn.createStatement.execute(createSQL2)
返回boolean值，表示是否创建成功。

2020-11-19 04:54 UTC, mdianjun commented on plugin-spark-sink-clickhouse/src/main/scala/io/github/interestinglab/waterdrop/spark/sink/Clickhouse.scala
> +  private def fieldTransform(dfField: StructField): Option[ClickHouseDataType] = {
函数名是 “动词+名词”的形式，如： acceptedClickHouseSchema。
比如改成 
```
convertToClickhouseDataType(dfType: DataType): Option[ClickHouseDataType] = {
```
输入是源类型，输出是目标类型。

2020-11-19 04:54 UTC, mdianjun commented on plugin-spark-sink-clickhouse/src/main/scala/io/github/interestinglab/waterdrop/spark/sink/Clickhouse.scala
> +      }
添加default分支处理异常：
```
case _ => throw 异常
```

2020-11-19 04:54 UTC, mdianjun commented on plugin-spark-sink-clickhouse/src/main/scala/io/github/interestinglab/waterdrop/spark/sink/Clickhouse.scala
> +            logInfo(String.format("table is not exists: %s, auto creating...", table))
table does not exist, auto creating ...

2020-11-19 04:54 UTC, mdianjun commented on plugin-spark-sink-clickhouse/src/main/scala/io/github/interestinglab/waterdrop/spark/sink/Clickhouse.scala
> +    val requiredOptions = List("host", "table", "database", "username", "password")
用户名、密码为什么是required？

2020-11-19 08:05 UTC, mdianjun commented on plugin-spark-sink-clickhouse/src/main/java/io/github/interestinglab/waterdrop/spark/sink/enums/ClickhouseEngineEnum.java
> +package io.github.interestinglab.waterdrop.spark.sink.enums;
hello

2020-11-19 09:11 UTC, mxzlxy commented on plugin-spark-sink-clickhouse/src/main/scala/io/github/interestinglab/waterdrop/spark/sink/Clickhouse.scala
> +  private def fieldTransform(dfField: StructField): Option[ClickHouseDataType] = {
fix

2020-11-19 09:11 UTC, mxzlxy commented on plugin-spark-sink-clickhouse/src/main/scala/io/github/interestinglab/waterdrop/spark/sink/Clickhouse.scala
> +            logInfo(String.format("table is not exists: %s, auto creating...", table))
fix

2020-11-19 09:12 UTC, mxzlxy commented on plugin-spark-sink-clickhouse/src/main/scala/io/github/interestinglab/waterdrop/spark/sink/Clickhouse.scala
> +    val requiredOptions = List("host", "table", "database", "username", "password")
fix

2020-11-19 09:12 UTC, mxzlxy commented on plugin-spark-sink-clickhouse/src/main/scala/io/github/interestinglab/waterdrop/spark/sink/Clickhouse.scala
> +    }
done

2020-11-19 09:12 UTC, mxzlxy commented on plugin-spark-sink-clickhouse/src/main/scala/io/github/interestinglab/waterdrop/spark/sink/Clickhouse.scala
>    override def checkConfig(): CheckResult = {
done

2020-11-19 09:12 UTC, mxzlxy commented on plugin-spark-sink-clickhouse/src/main/scala/io/github/interestinglab/waterdrop/spark/sink/Clickhouse.scala
>      }
done

2020-11-19 09:12 UTC, mxzlxy commented on plugin-spark-sink-clickhouse/src/main/scala/io/github/interestinglab/waterdrop/spark/sink/Clickhouse.scala
> +        }
done

2020-11-19 09:13 UTC, mxzlxy commented on plugin-spark-sink-clickhouse/src/main/scala/io/github/interestinglab/waterdrop/spark/sink/Clickhouse.scala
> +            new CheckResult(false, String.format("table %s is already exists, please check the table name, or set save_mode=\"overwrite\"", table))
fix

2020-11-19 09:13 UTC, mxzlxy commented
@mdianjun  PTAL

2020-11-19 10:38 UTC, godliness commented on plugin-spark-sink-clickhouse/src/main/scala/io/github/interestinglab/waterdrop/spark/sink/Clickhouse.scala
> +  private def convertToClickhouseDataType(dfType: DataType): Option[ClickHouseDataType] = {
convertToClickhouseDataType -> convertToClickHouseDataType

2020-11-19 10:38 UTC, godliness commented on plugin-spark-sink-clickhouse/src/main/scala/io/github/interestinglab/waterdrop/spark/sink/Clickhouse.scala
> +      case t: DecimalType => Option(ClickHouseDataType.Decimal)
t: 去掉 保持代码风格一致

2020-11-19 10:38 UTC, godliness commented on plugin-spark-sink-clickhouse/src/main/scala/io/github/interestinglab/waterdrop/spark/sink/Clickhouse.scala
> +              logInfo(String.format("table does not exists: %s, auto creating...", table))
logError or logWarn?

2020-11-19 10:55 UTC, godliness commented on plugin-spark-sink-clickhouse/src/main/scala/io/github/interestinglab/waterdrop/spark/sink/Clickhouse.scala
> +    engine match {
engine 有可能为null 这个要怎么处理？

2020-11-19 10:55 UTC, godliness commented on plugin-spark-sink-clickhouse/src/main/scala/io/github/interestinglab/waterdrop/spark/sink/Clickhouse.scala
> +      val tempArray = result.split("ENGINE = Distributed")(1).split(",")
tempArray 最好判断下是否空 因为依赖于标准输出还是有一定不稳定性的

2020-11-19 10:55 UTC, godliness commented on plugin-spark-sink-clickhouse/src/main/scala/io/github/interestinglab/waterdrop/spark/sink/Clickhouse.scala
> +      val tempArray = result.split("ENGINE = Distributed")(1).split(",")
result.split("ENGINE = Distributed")(1).split(",")  这里建议最好采用正则匹配 因为result.split("ENGINE = Distributed")(1)有可能数组越界  仅仅的是建议 如果确定这样没问题就好

2020-11-19 10:55 UTC, godliness commented on plugin-spark-sink-clickhouse/src/main/java/io/github/interestinglab/waterdrop/spark/sink/enums/ClickhouseSaveMode.java
> +    public static ClickhouseSaveMode fromName(String name) {
ClickhouseSaveMode -> ClickHouseSaveMode

2020-11-19 10:59 UTC, godliness commented on plugin-spark-sink-clickhouse/src/main/java/io/github/interestinglab/waterdrop/spark/sink/enums/ClickhouseSaveMode.java
> +        return null;
小心空指针

2020-11-19 11:09 UTC, godliness commented on plugin-spark-sink-clickhouse/src/main/scala/io/github/interestinglab/waterdrop/spark/sink/Clickhouse.scala
> +      conn.close()
conn 是否可能为 null

2020-11-20 02:15 UTC, mxzlxy commented on plugin-spark-sink-clickhouse/src/main/scala/io/github/interestinglab/waterdrop/spark/sink/Clickhouse.scala
> +              logInfo(String.format("table does not exists: %s, auto creating...", table))
这个不是错误也不是warn，是正常处理的逻辑，作为日志信息打印，默认逻辑会自动创建表

2020-11-20 02:17 UTC, mxzlxy commented on plugin-spark-sink-clickhouse/src/main/scala/io/github/interestinglab/waterdrop/spark/sink/Clickhouse.scala
> +    engine match {
engine枚举的string值后续是支持用户参数配置的，在外面匹配枚举的时候就会检查是否匹配成功，匹配失败直接报错

2020-11-20 02:25 UTC, mxzlxy commented on waterdrop-common/src/main/java/io/github/interestinglab/waterdrop/common/config/CheckResult.java
> +        return success;
这个是私有成员的getter方法，waterdrop会用这个方法判断result是否为真，编译器有提示缺失，我自动添加的，不加也可
![image](https://user-images.githubusercontent.com/34640335/99749901-4fa09480-2b1a-11eb-9e6a-42bc8d0ac4bd.png)

2020-11-20 02:49 UTC, mxzlxy commented on plugin-spark-sink-clickhouse/src/main/scala/io/github/interestinglab/waterdrop/spark/sink/Clickhouse.scala
> +      case t: DecimalType => Option(ClickHouseDataType.Decimal)
DecimalType这个去掉t会报类型不兼容，该类型待测试

2020-11-20 02:52 UTC, mxzlxy commented on plugin-spark-sink-clickhouse/src/main/java/io/github/interestinglab/waterdrop/spark/sink/enums/ClickhouseSaveMode.java
> +    public static ClickhouseSaveMode fromName(String name) {
Clickhouse是否全部换为ClickHouse，各个类名及插件名称也涉及修改

2020-11-20 03:15 UTC, mxzlxy commented on plugin-spark-sink-clickhouse/src/main/java/io/github/interestinglab/waterdrop/spark/sink/enums/ClickhouseSaveMode.java
> +        return null;
fix

2020-11-20 03:25 UTC, mxzlxy commented on plugin-spark-sink-clickhouse/src/main/scala/io/github/interestinglab/waterdrop/spark/sink/Clickhouse.scala
> +      conn.close()
fix，conn是在checkConfig里赋值，前面使用过，正常不会为空

2020-11-20 03:39 UTC, mxzlxy commented on plugin-spark-sink-clickhouse/src/main/scala/io/github/interestinglab/waterdrop/spark/sink/Clickhouse.scala
> +      val tempArray = result.split("ENGINE = Distributed")(1).split(",")
这里的结果格式目前遇到的情况较少，暂未找出比较鲁棒的规则，即使判断解析为空，也无法给出其他处理逻辑，还是会抛出异常，然后优化解析逻辑，已添加日志便于后续优化

2020-11-20 03:46 UTC, mxzlxy commented on plugin-spark-sink-clickhouse/src/main/java/io/github/interestinglab/waterdrop/spark/sink/enums/ClickhouseSaveMode.java
> +    public static ClickhouseSaveMode fromName(String name) {
讨论后指定统一规则为：类名相关用Clickhouse，方法名ClickHouse

2020-11-20 03:49 UTC, mxzlxy commented on plugin-spark-sink-clickhouse/src/main/scala/io/github/interestinglab/waterdrop/spark/sink/Clickhouse.scala
> +  private def convertToClickhouseDataType(dfType: DataType): Option[ClickHouseDataType] = {
done，讨论后指定统一规则为：类名相关用Clickhouse，方法名ClickHouse

2020-11-20 05:50 UTC, mxzlxy commented
@mdianjun PTAL

2020-11-20 06:31 UTC, godliness approved these changes

2020-11-20 06:31 UTC, godliness commented
LGTM

2020-11-27 07:02 UTC, mdianjun approved these changes

2020-11-27 07:04 UTC, merged